# Camera configuration (values + ranges). Ranges mirror settings.py.
auto_expo: false

# Auto Exposure Target
exposure: 16
exposure_min: 16
exposure_max: 220

# White balance temperature
temp: 10794
temp_min: 2000
temp_max: 15000

# White balance tint
tint: 925
tint_min: 200
tint_max: 2500

# Level ranges (RGBA). Min/max apply per channel.
levelrange_low: [0, 0, 0, 0]
levelrange_high: [255, 255, 255, 255]
levelrange_min: 0
levelrange_max: 255

contrast: 10
contrast_min: -100
contrast_max: 100

hue: 0
hue_min: -180
hue_max: 180

saturation: 45
saturation_min: 0
saturation_max: 255

brightness: -3
brightness_min: -64
brightness_max: 64

gamma: 100
gamma_min: 20
gamma_max: 180

# White balance gains (R, G, B). Min/max apply per channel.
wbgain: [0, 0, 0]
wbgain_min: -127
wbgain_max: 127

sharpening: 48
sharpening_min: 0
sharpening_max: 500

# 0/1; range is discrete but included for completeness
linear: 1
linear_min: 0
linear_max: 1

curve: Polynomial
fformat: tiff
