auto_expo: false
exposure: 16
temp: 10794
tint: 925
contrast: 10
hue: 0
saturation: 45
brightness: -3
gamma: 100
sharpening: 48
levelrange_low:
- 0
- 0
- 0
- 0
levelrange_high:
- 255
- 255
- 255
- 255
wbgain:
- 0
- 0
- 0
linear: 1
curve: Polynomial
fformat: jpeg
exposure_min: 16
exposure_max: 220
temp_min: 2000
temp_max: 15000
tint_min: 200
tint_max: 2500
levelrange_min: 0
levelrange_max: 255
contrast_min: -100
contrast_max: 100
hue_min: -180
hue_max: 180
saturation_min: 0
saturation_max: 255
brightness_min: -64
brightness_max: 64
gamma_min: 20
gamma_max: 180
wbgain_min: -127
wbgain_max: 127
sharpening_min: 0
sharpening_max: 500
linear_min: 0
linear_max: 1
